### ISSUE TITLE
End Dogs and Nether Dogs should spawn in there respective dimensions 

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#11]

**Comment by LyraelRayne** [comment]
End wolves spawn in the End. As a bonus, Ice wolves no longer spawn in the End... oops :P

Nether and End wolves weren't spawning in the nether/end because grass doesn't appear there. I have fixed #7 which seems to have fixed this too.

Ender wolves still spawn at night time in the overworld just like enderment.
