### ISSUE TITLE
[Feature Request]Blaze wolves leave a fire trail and spawn in nether fortresses only 

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#12]

**Comment by LyraelRayne** [comment]
I made the particle effects denser so that it looks like there's a trail of fire when they move. Leaving a trail of actual fire might be a bit too difficult in the time we have. Also I think it'd be a bit more destructive to the world than one might want.

Fire wolves now spawn in the nether fortresses only.
