### ISSUE TITLE
[Bug] Spawning Issues

### ISSUE THREAD

**Issue by Jaspanda** [LyraelRayne/StacysWolves#15]
There's a few spawning issues I've come across so far (Version 1.0.1):

**Ice wolf**\- Spawns in a normal taiga (should only spawn in cold biomes)

**Ore wolves** (all of them)- Can't find any of them

**Prismarine wolf**\- Can't find any in the ocean

**Water wolf**\- Spawns underground sometimes

**Cake wolf**\- Many spawn in a dessert, not a village

**Mushroom wolf**\- Doesn't spawn in dark oak forest with the big mushrooms

**Birch wolf**\- Spawns in taigas (should only spawn in biomes with birch trees present)

**Comment by LyraelRayne** [comment]
Those all got fixed in 1.0.3 or 4 (1.0.1 spawns were pretty horrible, I just wanted it out there and to have some early feedback). 

I can't do much with prismarine wolves. I've been coding with Vanilla 1.7 which obviously doesn't have prismarine anything.  Unfortunately I don't have time right now to figure out how to make et futurum an optional dependency and work with it. I left the wolves in the mod in case someone wanted to do something with minetweaker, etc. to add recipes and spawns for them.

I presume you mean the roofed forests for the mushroom wolf?

**Comment by SnowShock35** [comment]
Yes  @LyraelRayne roofed forests. The mushroom one should spawn scarcely in there as mushroom islands are really difficulty to find compared to roofed forests.

**Comment by LyraelRayne** [comment]
Well they spawn in those now, so all good.

**Comment by SnowShock35** [comment]
Okay in that case. Ty issue shall be closed!
