### ISSUE TITLE
Tons of Mushroom Wolves

### ISSUE THREAD

**Issue by Jaspanda** [LyraelRayne/StacysWolves#18]
So uh.. this happens when mushroom wolves spawn.. bit excessive

![image](https://cloud.githubusercontent.com/assets/18662539/14796261/6749bf5c-0afa-11e6-9dda-951fb6ef21e0.png)

**Comment by SnowShock35** [comment]
I wouldn't say that's too bad but yeah maybe needs toning down a little :stuck_out_tongue:

**Comment by LyraelRayne** [comment]
I might trial these as a "creature" spawn type. the problem with monster spawn type is that you can have 70 monsters in a given area (and nothing else spawns here during the day) so you end up with HEAPS. 

Creature spawn type doesn't seem to spawn randomly very often, but does spawn with worldgen. It also has a limit of 15 in a given area which is far more manageable. On the downside, because they spawn in worldgen it doesn't check most of the regular spawning conditions. Probably not a problem for these guys though.

**Comment by LyraelRayne** [comment]
OK I pushed the code to hopefully make these guys more scarce. @SnowShock35  can you give it a test?

**Comment by SnowShock35** [comment]
@LyraelRayne When u fix the issue with biomes o plenty sure :stuck_out_tongue:
