### ISSUE TITLE
[Feature Request] Prismarine Wolves Spawn in Deep Ocean Biome

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#20]
Hi Lyrael,

I know we've discussed this multiple times but if you're able to make a small pack or two spawn in deep oceans that would be great.

If not, perhaps same as where ocean wolves spawn in beaches?

**Comment by LyraelRayne** [comment]
Making Prismarine Wolves spawn in deep ocean is doable, but there's a bit of an issue with it.

The wolves don't walk on the bottom of the ocean. Meaning that you'll just have random wolves spawning in the middle of the ocean and swimming around trying to find land. The rendering (of both Stacy's and Vanilla) wolves goes a bit funky when they're swimming and I don't know how to fix that. This is why I made Ocean Wolves spawn on the shore.

I could make the Prismarine Wolves spawn where the Ocean Wolves do just more rare, that's easy; but I think it's more important to fix spawning in general first.

I still can't make a recipe with Prismarine in it, so you'd need to minetweaker a recipe for the prismarine bone to tame the wolves.

**Comment by LyraelRayne** [comment]
I've told the wolfies to spawn in the deep ocean biome. Haven't found a deep ocean to test it in. I'm going to have a quick look to see if I can find a way to actually make them spawn in the ocean monuments seeing as Stacy seems so keen on having them work plus watching the mod spotlight inspired me :P Still no idea how I'd do it though.

**Comment by LyraelRayne** [comment]
Good news: I now have the wolves spawning in the Ocean Monuments. Or rather, they'll spawn anywhere in the deep ocean biome as long as there are prismarine blocks directly above and below it. 

Prismarine Bone now has a recipe too.

Both of these only work when Et Futurum is installed. 

The bad news is that the rendering of wolves underwater is poor in general (something to do with the lighting). I want to fix this before we release them.

The other non-ideal thing is that the wolves just try to swim straight upwards to the surface. I'd like to make it so that they can walk underwater somehow but that's beyond what I can do this weekend.

**Comment by SnowShock35** [comment]
@LyraelRayne Okay thank you Lyrael. :-)

**Comment by LyraelRayne** [comment]
Prismarine wolves will spawn in ocean monuments as of 1.0.7!
