### ISSUE TITLE
StacyWolves Possible Bug 

### ISSUE THREAD

**Issue by JCP15** [LyraelRayne/StacysWolves#29]
Hi whomever reads this, 

So I had a little conversation with Alex regarding a possible bug I'm having with the Stacywolves mod. After I updated the mod, I had the ender wolves going crazy and teleporting everywhere without being hit or anything. When I settle down, I don't know if the specific area I settle is ender wolves galore but every day I would have 5+ untamed wolves teleporting all over my house. Also one time I was out and was attack by a modded mob and I was pretty far away and my tamed ender solve teleported and started attacking it as if it was a normal MC wolves. I don't know if there is more info you guys might need, or if its in the correct format ... Sorry if it isn't. 

Thanks 

John

**Comment by LyraelRayne** [comment]
Hi there, Thanks for the feedback.

I've reviewed the Ender Wolf teleporting done the following:
- Ender wolves no longer blindly walk into water when not tamed. (they'd walk into water and then teleport because they were hurt).
- Ender wolves are no longer teleport crazy. They will now only have a 20% chance of teleporting once every 5 seconds. Previously it was checking every tick with a 2% chance.
- Ender wolves will now teleport when chasing a bone.
- Ender wolves no longer randomly teleport when chasing prey or a bone.
- Ender wolves will under no circumstances teleport while sitting.

Ender wolves are intended to behave like vanilla wolves with regard to their attacking things which are in combat with their master. However now if you leave your wolfie sitting at home, it won't teleport to your rescue.

Try 1.0.11 and let me know if that works better for you.
