### ISSUE TITLE
You can tame wolves with any item it seems (Well any bone/apple) 

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#3]
I was able to tame the creatures with any item. Assuming a check was missed

**Comment by LyraelRayne** [comment]
I officially fail my boolean algebra tutorial. I forgot that AND happens before OR and therefore my check was 

"If the food is the same class and the food has no subtypes, OR if the metadata was the same as the desired item"

Should have been
"If the food is the same class then see if it has subtypes. If it does, check the metadata matches, otherwise it's good".
