### ISSUE TITLE
Wolves Wont Spawn Anywhere

### ISSUE THREAD

**Issue by IAmBenM** [LyraelRayne/StacysWolves#35]
Hey,

I have downloaded this mod just today to play on my modded survival but unfortunately no wolves spawn naturally.  I was really hoping you can help me and tell me why they wont spawn.

Thank You IAmBenM
P.S. I am using version 1.0.13

**Comment by LyraelRayne** [comment]
Hi,

Are you still having this problem? It takes a while for wolves to start showing up on new worlds (other than the zombie, skeleton and ender wolves) because they spawn the same way as pigs and sheep and cows (i.e. not very often). I also think they won't spawn underneath trees (because they detect being "outdoors" by being "under" the sky with no obstruction).

Another thing to check is whether /gamerule doMobSpawning = 1  (see http://minecraft.gamepedia.com/Commands#gamerule) and that your game isn't in peaceful mode.

**Comment by LyraelRayne** [comment]
See #36
