### ISSUE TITLE
Wolves are not spawning correctly?

### ISSUE THREAD

**Issue by saltworthybutler** [LyraelRayne/StacysWolves#40]
I'm not sure the wolves are spawning correctly in my world. They seem to spawn just fine in groups if I create a superflat world other than that I am not sure what's wrong. I'm a bit of a scaredy cat so I play in survival mode but turn mobSpawning off so I still have hunger. I've tried creating worlds in creative and turning them to survival as well as vice versa. Sometimes I'll see one or two if I start the world off in creative but other than that they just seem super rare but most of the time I don't even see them at all. Below is just a clipping of the mods I'm using I am definitely no tech or computer expert. I'm using Forge 10.13.4.1558 for 1.7.10, I would leave that Forge log that you stated you wanted in your post but in all honesty I don't know how to get that so if you need it then I may need some direction on where to find it. If you have any idea what's up please let me know when you have a moment. Thank you!

![mod list](https://user-images.githubusercontent.com/40327036/41503372-0a034c80-7198-11e8-81a9-3a472efc3c04.JPG)

**Comment by LyraelRayne** [comment]
The game rule doMobSpawning governs ALL spawning of any kind of mob (which actually means "mobile creature", not "monster" as many people seem to think). This includes passive mobs (cows, sheep, etc.) hostile mobs (zombies, skeletons, etc.) and any other kind of mob (including Stacy's Wolves). Turning it off will thus prevent spawning of Stacy's Wolves. 

If you turn off spawning, passive type mobs will still be found in your world because some of those are included in world generation. The only way you'll get any more is to breed them. Stacy's Wolves are not part of world generation so you won't find any at all with doMobSpawning = false.

I think the reason you're seeing them in superflat is because you'd be hard pressed to manage to turn off doMobSpawning before some wolves spawned, whereas in a normal survival world it takes a while before any will spawn. 

If you would still like to play with Stacy's Wolves; but without scary monsters ruining your perfectly good world then you may wish to install a mod such as https://minecraft.curseforge.com/projects/bad-mobs to have more control over which mobs are allowed to spawn in your world.

**Comment by saltworthybutler** [comment]
Lmao thank you so much I knew it was me lol. Have a good day!
