### ISSUE TITLE
Desert, Mesa and Ocean wolves spawning is somewhat 'broken'

### ISSUE THREAD

**Issue by SnowShock35** [LyraelRayne/StacysWolves#7]
I believe that because passive mobs only spawn on dirt/grass (Where there's little to none of this block in the biomes they spawn in there aren't any really spawning

**Comment by LyraelRayne** [comment]
I think it's actually just that they spawn more rarely. Might remove this from everything but the cake wolf that was meant to be REALLY rare.

**Comment by LyraelRayne** [comment]
Ocean wolves actually spawn as "water creature". Might need to see if something is preventing them spawning in water. Otherwise I'll just make them spawn on the beach as normal creatures.

**Comment by LyraelRayne** [comment]
Ocean wolves look kinda bad in the ocean so I just made them spawn on the beach and on land in ocean biomes.

Also removed the dirt/grass check from the spawning logic for all wolf types. Now they'll spawn on anything in their respective biomes.

Also removed "creature" type from the cake wolves because I can't figure out how to make creatures spawn frequently enough.
